name: "Upload components"
description: "Upload components to Espressif IDF component registry"
branding:
  icon: upload
  color: red
inputs:
  api_token:
    description: "API Token for the component registry"
    required: true
  namespace:
    description: "Component namespace"
    required: true
  directories:
    description: "Semicolon separated list of directories with components to upload"
    required: false
  name:
    description: "Name of the component. Required, if `directories` are not set.
      If `directories` contain more than 1 location,
      the name of the component directory is used instead and `name` is ignored."
    required: false
  version:
    description: "Version of the component, if not specified in the manifest. Can be a semantic version or `git` for getting version from git tag."
    required: false
  service_url:
    description: "Component registry API endpoint"
    required: false
  registry_url:
    description: "Component registry endpoint"
    required: false
  skip_pre_release:
    description: "Flag to skip pre-release versions. Set it to any non-empty string to skip pre-release versions."
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    COMPONENTS_DIRECTORIES: ${{ inputs.directories }}
    COMPONENTS_NAMESPACE: ${{ inputs.namespace }}
    COMPONENT_NAME: ${{ inputs.name }}
    COMPONENT_VERSION: ${{ inputs.version }}
    IDF_COMPONENT_API_TOKEN: ${{ inputs.api_token }}
    DEFAULT_COMPONENT_SERVICE_URL: ${{ inputs.service_url }}
    IDF_COMPONENT_REGISTRY_URL: ${{ inputs.registry_url }}
    SKIP_PRE_RELEASE: ${{ inputs.skip_pre_release }}
